import type { Metadata } from "next";

import DashboardWrapperProvider from "./DashboardWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DashboardWrapperProvider> {children}</DashboardWrapperProvider>;
}
